apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-node-app
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL:https://github.com/rakshithbs24/my-node-app.git
    path: my-node-app  
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
